# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
