# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
    	migrations.RenameModel("Post", "Day")
    ]
